try:
    print(i)
except NameError:
    print("i not found exeption occured")